#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server to send traffic to both web-01 and web-02
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s "frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 2152-web-01 35.196.31.36:80 check
    server 2152-web-02 35.237.103.48:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
