#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server to send traffic to both web-01 and web-02
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
    balance roundrobin
    server 4970-web-01 54.227.11.69:80 check
    server 4970-web-02 34.229.17.111:80 check
frontend http
    bind *:80
    mode http
    default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
