#!/usr/bin/env bash
#iDebug to ensure server listens on port 80
sudo apt-get -y update
sudo apt -y install nginx
sed -i  's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx startt
sudo service nginx restart
